### ISSUE TITLE
unable to route to any route

### ISSUE THREAD

**Issue by kamaroly** [atrakeur/laravel-forum#12]
I am trying to point to localhost:8080/forum but this expection is being threw Symfony \ Component \ HttpKernel \ Exception \ NotFoundHttpException

how can I start working using this package?

**Comment by atrakeur** [comment]
Well I've just checked and the installation instructions are correct for laravel 4.1 and 4.2.
Have you run php artisan forum:install to create the forum's controllers inside your application namespace? 

If the above command doesn't run, make sure you have added the service provider into your app.php config file?

Good luck and let me know if it still doesn't work.

**Comment by kamaroly** [comment]
Thank you atrkeur, 
Can you share with me the routes you use for the forum , forexample the route to add new category etc...

**Comment by atrakeur** [comment]
The routes are available in vendor/atrakeur/forum/routes.php.
There is no routes to create categories on the fly. You have to use migrations (and seeding) to create appropriate data before startup.
I was planning with an integration with frozennode/administrator to help in that task. But I think it's a better idea to have Categories in files (and under version control).

**Comment by kamaroly** [comment]
Thanks , It is working. I didn't add categories and subcategories to the db. That was the issue. I think it's better to add a seed for the db.
